[package]
name = "guess_number_first"
version = "0.1.0"
edition = "2021"
authors = ["Tommylee"]

# See more keys and their d efinitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"


